HealthTargetProfiles = [
    "Procurement of wearable ECG patches for continuous cardiac monitoring in community care settings.",
    "Supply of smartwatch-based vital signs monitors for remote patient monitoring programmes.",
    "Tender for body-worn biosensors capable of measuring SpO2, heart rate, and respiratory rate.",
    "Provision of continuous glucose monitoring wearables for diabetes management in primary care.",
    "Supply of wearable blood pressure monitors for ambulatory hypertension management.",
    "Procurement of fall-detection wearable devices and personal alarm systems for elderly patients.",
    "Tender for clinical-grade wrist-worn patient monitors with real-time telemetry capability.",
    "Supply of adhesive biosensor patches for post-surgical remote recovery monitoring.",

    "Provision of body-worn patient monitoring wearables for hospital-at-home and virtual ward programmes.",

    "Tender for telehealth wearables supporting home-based management of chronic conditions.",
    "Supply of IoMT-enabled wearable devices for real-time patient physiological data capture.",
    "Procurement of biometric monitoring systems for digital health and mHealth platforms.",
    "Wearable health technology for continuous monitoring of elderly and high-risk patients at home.",
    "Provision of a digital health analytics platform with integrated wearable biosensor devices.",
    "Tender for AI-powered wearable monitoring solutions with predictive health analytics.",
    "Supply of wearable rehabilitation devices for gait, posture, and movement monitoring.",
    "Procurement of connected medical devices enabling real-time vitals and physiological analytics.",
    "Wearable fatigue and stress monitoring solution for healthcare workforce wellbeing programmes.",
    "Supply of medical-grade wearable sensors for biosignal acquisition and physiological monitoring.",
    "Tender for wireless patient monitoring systems with body-worn sensor and cloud analytics.",
    "Provision of edge-AI wearables capable of on-device biosignal processing and anomaly detection.",
    "Smart textile garments with embedded sensors for continuous health and activity monitoring.",
    "Procurement of multiparameter wearable monitors for sleep, recovery, and vital signs tracking.",
]
CorporateTargetProfiles = [
    "Procurement of industrial wearable sensors for worker fatigue and heat stress monitoring on-site.",
    "Supply of smart PPE with integrated biosensors for real-time occupational health monitoring.",
    "Tender for connected safety wearables detecting hazardous gas exposure in industrial environments.",

    "Supply of body-worn wearable sensors for personal radiation and chemical exposure monitoring in hazmat environments.",

    "Provision of lone-worker monitoring wearables with location tracking and physiological alerts.",
    "Corporate wellness platform procurement including wearable biometric devices for employee health tracking.",
    "Tender for workforce wellness wearables providing fatigue analytics and wellbeing insights to employers.",
    "Supply of employee health monitoring devices for occupational health and safety compliance programmes.",
    "Provision of wearable stress and ergonomic monitoring solutions for office and field employees.",
    "Supply of construction site wearable monitoring devices for worker vital signs and safety compliance.",
    "Procurement of wearable sensors for factory and warehouse worker physiological and location monitoring.",
    "Tender for oil-and-gas field worker wearables with environmental and biometric monitoring capability.",
    "Mining industry supply of connected wearable safety equipment with real-time physiological telemetry.",
    "Provision of industrial IoT wearable platform for workforce health analytics and safety dashboards.",
    "Tender for connected worker platform integrating wearable sensors with occupational health data systems.",
    "Supply of smart safety vest and connected helmet solutions for industrial worker monitoring.",
    "Procurement of wearable-based occupational analytics platform for workforce risk and compliance reporting.",
    "Industrial remote monitoring solution using body-worn sensors for distributed field workforce management.",
    "Provision of corporate wearable telemetry system for real-time worker location and wellness monitoring.",
    "Tender for ergonomic wearable monitoring system to reduce musculoskeletal injury risk in the workplace.",
]
DefenceTargetProfiles = [
    "Procurement of wearable physiological monitoring systems for battlefield soldier readiness assessment.",
    "Supply of military-grade body-worn biosensors for real-time warfighter vital signs monitoring.",
    "Tender for tactical wearable sensors measuring soldier heart rate, SpO2, and core temperature.",
    "Provision of soldier telemetry devices for remote physiological monitoring during field operations.",
    "Supply of combat-ready wearable health monitors for troop fatigue and stress assessment.",

    "Wearable system for continuous monitoring of warfighter readiness and mission endurance.",
    "Tender for defence physiological monitoring platform tracking combat unit health and performance.",
    "Procurement of military biosensor wearables for battlefield medical triage and casualty monitoring.",
    "Supply of connected tactical wearables providing real-time human performance analytics to commanders.",

    "Defence programme for AI-enabled wearable analytics supporting warfighter performance optimisation.",
    "Tender for military biometric monitoring systems with encrypted telemetry and command integration.",
    "Provision of battlefield physiological analytics platform with soldier-worn sensor integration.",
    "Supply of wearable situational awareness devices for combat personnel location and health tracking.",

    "Procurement of ruggedised body-worn sensors meeting military operational environmental standards.",
    "Tender for wearable combat systems with physiological data fusion and tactical decision support.",
    "Supply of smart soldier systems integrating biometric wearables with digital command networks.",
    "Military remote monitoring solution for deployed personnel physiological and cognitive state tracking.",
    "Provision of field-deployable wearable telemetry for real-time soldier biodata collection and analysis.",
    "Tender for advanced human performance monitoring wearables for special operations forces.",
    "Defence acquisition of wearable biosensing platforms for operational health surveillance programmes.",
]
PetsTargetProfiles = [
    "Procurement of smart pet collars with GPS tracking and health monitoring for dogs and cats.",
    "Supply of wearable activity and vital signs trackers for companion animal wellness monitoring.",
    "Tender for connected pet wearables measuring heart rate, temperature, and activity levels.",
    "Provision of veterinary wearable devices for remote monitoring of post-operative pet recovery.",
    "Supply of pet cardiac and respiratory monitoring wearables for use in veterinary clinics.",

    "Procurement of livestock wearable biosensors for real-time cattle health and activity monitoring.",
    "Supply of smart livestock collars for dairy herd physiological monitoring and reproductive tracking.",
    "Tender for equine wearable telemetry systems monitoring horse heart rate, gait, and performance.",
    "Provision of farm animal monitoring platform with wearable sensors for livestock health analytics.",
    "Livestock telemetry procurement for remote physiological and location monitoring of grazing cattle.",

    "Supply of veterinary biosensor platform integrating wearable animal sensors with health analytics.",
    "Tender for AI-enabled animal health monitoring system using wearable physiological sensors.",
    "Connected pet health platform with wearable device integration for real-time wellness tracking.",
    "Provision of smart livestock management system incorporating wearable sensors and predictive analytics.",

    "Supply of animal-worn ECG and SpO2 monitoring devices for veterinary diagnostic applications.",
    "Procurement of wearable equine biosensors for performance monitoring and injury prevention.",
    "Tender for GPS-enabled smart harness with biometric monitoring for working and service dogs.",
    "Supply of veterinary telemetry wearables for continuous remote monitoring of critically ill animals.",
    "Provision of wearable environmental and physiological sensors for zoo and wildlife health monitoring.",
    "Animal activity and location tracking wearable solution for large-scale livestock farm management.",
]